# ffmpeg video source
video: ~

audio:
    source: http://10.32.0.126:8000/insanity320.mp3
    encoder: DASH::Encoder::FFmpeg
    codec: libvorbis
    bitrates:
        - 128k
        - 256k


# Absolute path to the webroot. NEEDS A TRAILING SLASH
root: /var/www/html/dash/insanity/
chunk_length: 10000
history: 3600000


logging: Logger::DEBUG